[workspace]
authors = ["kaspermunch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "bioconda", "munch-group"]
name = "pca-admixture-exercise"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.2.0,<8"
nodejs = ">=25.6.0,<25.7"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.8.0,<2"
sgkit = ">=0.10.0,<0.11"
bio2zarr = ">=0.1.7,<0.2"
vscodenb = ">=0.1.34,<0.2"
admixture = ">=1.3.0,<2"
cartopy = ">=0.25.0,<0.26"
quarto = ">=1.7.33,<2"
nbdime = ">=4.0.4,<5"
git = ">=2.52.0,<3"

